### ISSUE TITLE
Inconsistency in the BFP APIs for 16/32 bit BFPs when using scalar arguments

### ISSUE THREAD

**Issue by andrewxcav** [xmos/lib_xs3_math#91]
- bfp_s16/s32_set, bfp_s16_add_scalar, bfp_s16/s32_clip specify scalar arguments as mantissa-exponent pairs,
- bfp_s16_scale uses a plain float argument,
- bfp_s32_add_scalar, bfp_s32_scale use a float_s32_t struct for passing mantissa-exponent pairs.

This becomes particularly visible with add_scalar and scale when converting 16-bit code to 32-bit or vice versa, as the 16/32-bit APIs use different argument types.

**Comment by astewart-xmos** [comment]
This was partly intentional, though I have mixed feelings about it and I can certainly see why it's confusing/messy.

A couple inconvenient facts: 
* the IEEE754 single-precision `float` type has 23 bits of significand.
* we don't natively support double-precision floats

Because of this, both `float` and `double` are unsuitable for use as a scalar in 32-bit operations. The former because it could significantly reduce precision, and the latter because it could significantly reduce performance.

`float`, however, is suitable for use as a scalar in 16-bit (high-level API) operations, and is probably the most intuitive type to use where it is suitable. 

The `float_s32_t` type is meant to be the 32-bit scalar parallel to `float` for 16-bit ops.

At the moment I'm thinking the `bfp_sXX_set()` functions should probably use `float` and `float_s32_t` for their values. I imagine that was an oversight.  

The `bfp_sXX_clip()` functions intentionally separate the exponent and mantissas. Because each function requires upper and lower bounds, separating exponent and mantissas in this way forces use of a shared exponent, which significantly simplifies these functions.

The `bfp_sXX_scale()` and `bfp_sXX_add_scalar()` functions should all use the combined mantissa/exponent types (`float` and `float_s32_t`), which they currently do.  (You mentioned `bfp_s16_add_scalar()` takes mantissa-exponent pairs, but on [`develop`](https://github.com/xmos/lib_xs3_math/blob/develop/lib_xs3_math/api/bfp/bfp_s16.h#L241) it takes a `float`)

---

I'm open to debate here. Like I said, I'm not in love with it.

In particular, is it worth using the native `float` type for 16-bit operations, or should should there be a `float_s16_t`, so that the 16-bit API more closely matches the 32-bit API?

**Comment by astewart-xmos** [comment]
Just so that it isn't lost in the comment above, I do think **the `bfp_sXX_set()` functions should probably be changed to take the combined mantissa/exponent types**.

However, it's not a backwards-compatible change, and so it would require a major version increment of the library, which would be quite unfortunate.

To avoid needing to increment the major version of the API, we could introduce a macro  `LXM91` (lib_xs3_math issue #91), undefined by default, and where if defined and nonzero, the new form of the functions are defined instead.  This leaves the API backwards compatible unless a user has explicitly opted-in to the new form.

**Comment by astewart-xmos** [comment]
**Question:  Should the 16-bit scalars use the native `float`  type, or should a `float_s16_t` struct (analogous to `float_s32_t`) be introduced to keep the API more consistent?**

Looking for feedback from anyone interested.

**Comment by andrewxcav** [comment]
> Just so that it isn't lost in the comment above, I do think **the `bfp_sXX_set()` functions should probably be changed to take the combined mantissa/exponent types**.
> 
> However, it's not a backwards-compatible change, and so it would require a major version increment of the library, which would be quite unfortunate.
> 
> To avoid needing to increment the major version of the API, we could introduce a macro `LXM91` (lib_xs3_math issue #91), undefined by default, and where if defined and nonzero, the new form of the functions are defined instead. This leaves the API backwards compatible unless a user has explicitly opted-in to the new form.

Could you just have an overloaded version of the function and then deprecate the old one as a minor release before doing a major version bump?

Since this is a source library written in c++ I don't think this would increase code size, but I tend to credit compilers with some serious magic.

**Comment by astewart-xmos** [comment]
> Could you just have an overloaded version of the function and then

It's all written in C so overloading isn't an option :(

**Comment by astewart-xmos** [comment]
I've given this some thought, and I think this is just one part of a broader need for refactoring. A major version increment is due to be published, so it's probably a good time for it.

I've created an [issue](#103) for the broader change, so I'm going got just close this one.
