### ISSUE TITLE
Suggested new function bfp_s32_add_s16

### ISSUE THREAD

**Issue by andrewxcav** [xmos/lib_xs3_math#92]
bfp_s32_add_s16, which adds a BFP of 16-bit values to a 32-bit BFP

When accumulating large numbers of 16-bit BFPs that aren't necessarily zero mean this would remove the need to stop and copy out to a 32-bit value to retain precision.

This is of course only useful if it can be done more efficiently than converting/accumulating manually.

**Comment by astewart-xmos** [comment]
I would suggest an alternative approach.

Converting 16-bit vectors to 32-bit vectors is not something that XS3 is especially good at. The most efficient way to do it [using the VPU](https://github.com/xmos/lib_xs3_math/blob/develop/lib_xs3_math/src/arch/xcore/xs3_vect_s16_to_s32.S#L53) that I'm aware of is not that much more efficient than using the scalar unit.

**Question: Do you need to use the 32-bit BFP vector result _between_ accumulations?**

If not (and possibly even if so, but we'd need to talk about that) I propose a low-level function `xs3_vect_s16_foo()` whose arguments are:
- An input/output vector of [`xs3_split_acc_s32_t`](https://github.com/xmos/lib_xs3_math/blob/develop/lib_xs3_math/api/xs3_math_types.h#L415-L432)
- An input vector of `int16_t`
- several other parameters for exponents/headroom/shifts 

Each call to `xs3_vect_s16_foo()` would just `VLMACC` the provided 16-bit vector into the split accumulators (`vD`:`vR`), but would _not_ do a `VLSAT` to get 16-bit values out, or convert the split accumulators into a 32-bit vector.
The function would return the headroom of the split accumulator vector. 

When the headroom of the split accumulator vector gets too low (i.e. 1 bit), the next accumulation could potentially saturate, and so some other function `xs3_vect_split_s32_bar()` would shift down the accumulator to make room for more accumulation.

Finally, when it's time to get back a 32-bit vector, you just use [`xs3_vect_s32_merge_accs()`](https://github.com/xmos/lib_xs3_math/blob/develop/lib_xs3_math/api/vect/xs3_vect_s32.h#L2160-L2186).

If you need to use the 32-bit vector between 16-bit accumulations this approach might not work.

**Comment by andrewxcav** [comment]
Values wouldn't be needed between accumulations, the goal would just be to keep accumulating for as long as possible (assuming the headroom check is cheaper than just picking a safe number of accumulations to do per batch).

**Comment by astewart-xmos** [comment]
This has been committed and will be merged with PR #98.

The function to look for is [`bfp_s16_accumulate()`](https://github.com/astewart-xmos/lib_xs3_math/blob/develop/lib_xs3_math/api/bfp/bfp_s16.h#L875-L942). It takes an array of xs3_split_acc_s32_t` structs which serve as the accumulators and a `bfp_s16_t` which gets accumulated into the other.

Two tricky bits. First, is that the user has to manage the headroom of the accumulator vectors. The second is that the exponent associated with the accumulators needs to stay within `14` of the exponent of each `bfp_s16_t` vector. 

Regarding the former, each call to `bfp_s16_accumulate()` returns the headroom of the accumulators. If this is greater than 0 -- if there is at least 1 bit of headroom -- then the net call to `bfp_s16_accumulate()` is guaranteed not to saturate (minding the exponent constraint). If 0 is returned, it's possible for the next accumulation to saturate. 

At that point, if more vectors need to be accumulated, you can call `xs3_vect_split_acc_s32_shr()` to right-shift the accumulator vectors by some number of bits. Then, increment the exponent by the same amount. This will make more room in the accumulators, and because the exponent is now larger, they'll grow more slowly.

Right-shifting the accumulators is fairly expensive, so it's probably worthwhile, when possible, to choose an initial accumulator exponent that won't require any shifting.
