### ISSUE TITLE
New function suggestion: bfp_s16/s32_scale_add 

### ISSUE THREAD

**Issue by andrewxcav** [xmos/lib_xs3_math#93]
bfp_s16/s32_scale_add function that multiplies a BFP with a scalar, then adds the result to another BFP. 

The matching swapped function that adds a scalar, then multiplies a BFP would be useful as well. 

Sort of like the existing bfp_s16_nmacc and bfp_s16_macc functions, but for scalars.

**Comment by astewart-xmos** [comment]
For  32-bit, this would be achieved as:

**Comment by astewart-xmos** [comment]
Can I ask what advantage you're looking to get from this?

Currently your best bet is just to do:

```c
  bfp_sXX_scale(out_vec, init_vec, scale_val);
  bfp_sXX_add(out_vec, out_vec, add_vec);
```

There are 2 options for implementing a `bfp_sXX_scale_add()`.

The first is to just wrap the above two lines into a single function call. I'd prefer not to do this because all it does it increase the surface area of the library without adding any significant benefit.

The second is to create a new low-level function `xs3_vect_sXX_scale_add()` which can then by called by `bfp_sXX_scale_add()`.  I haven't studied this closely enough to determine yet whether this can result in a noticeable performance improvement.  I'm still doubtful, though, that any improvement would outweigh the additional surface area + development effort.

If this operation is currently the performance bottleneck in some important process, we should chat about it to see what makes sense.

**Comment by andrewxcav** [comment]
I think using the two functions makes sense unless there was a major performance boost from a fused function.
